### ISSUE TITLE
Homepage not working

### ISSUE THREAD

**Issue by ottlinger** [apache/drat#103]
http://drat.apache.org/
yields a 404 at the moment.

As one of the RAT developers I got curios about DRAT .....

**Comment by chrismattmann** [comment]
thanks @ottlinger see #98 for current status and for contributions there. Closing as duplicate.

**Comment by ottlinger** [comment]
@chrismattmann thanks for letting me know, maybe there should at least be some kind of "work in progress" instead of a 404 .... the design mention in #98 looks very nice :-)

**Comment by chrismattmann** [comment]
agree @ottlinger - please come on over to #98 and let's discuss. Can you help put up an "under construction page." Until #98 is done?
