### ISSUE TITLE
DRAT Proteus build failure on Ubuntu 16.04

### ISSUE THREAD

**Issue by ThejanW** [apache/drat#104]
I am getting errors with TestProcessDratWrapper test class. Attaching the full error log here.
[build.log](https://github.com/apache/drat/files/1465136/test.log)

**Comment by chrismattmann** [comment]
Make sure you have the these [environment variables](https://github.com/apache/drat/wiki/Installation#useful-environment-variables) set. Try building after that.

**Comment by chrismattmann** [comment]
@ThejanW

**Comment by ThejanW** [comment]
Oh! didn't notice that. thanks @chrismattmann :+1:

**Comment by chrismattmann** [comment]
awesome. Can you confirm this fixed your issue @ThejanW and that it builds?

**Comment by chrismattmann** [comment]
ping @ThejanW did it build?

**Comment by chrismattmann** [comment]
ping @ThejanW

**Comment by ThejanW** [comment]
@chrismattmann I am sorry, I couldn't comment on this soon enough.
Yes, it built fine, once I exported the correct variables, thanks @chrismattmann.  A future user might benefit from this issue.
I'm attaching the build log I generated with mvn -X 
[build.log](https://github.com/apache/drat/files/1490400/build.log)

**Comment by chrismattmann** [comment]
fixed
