### ISSUE TITLE
ProcessDratWrapper has an unmet dependency CommonsHttpSolrServer

### ISSUE THREAD

**Issue by IMS94** [apache/drat#112]
At [line 414](https://github.com/apache/drat/blob/master/proteus/src/main/java/backend/ProcessDratWrapper.java#L414), the class CommonsHttpSolrServer (Came in 1.x) is no longer available in the current solrj version used by DRAT (4.x). It has been replaced with HttpSolrServer in 4.x.

Due to this problem, maven build fails.

**Comment by chrismattmann** [comment]
@IMS94 odd it builds for me? And when I look at Solr 4.2.1, I see you are right: http://lucene.apache.org/solr/4_2_1/solr-solrj/org/apache/solr/client/solrj/impl/HttpSolrServer.html oddly though it builds fine?

**Comment by chrismattmann** [comment]
builds fine for me... @IMS94 can you try again?

**Comment by chrismattmann** [comment]
this works fine
