### ISSUE TITLE
Integrate https://github.com/nexB/scancode-toolkit into DRAT as an option

### ISSUE THREAD

**Issue by chrismattmann** [apache/drat#113]
Instead of only using RAT, we can also use https://github.com/nexB/scancode-toolkit.
Simple replacement in the PGE. 
This is a Google Summer of Code project for 2018. Comment here if interested.

**Comment by ThejanW** [comment]
Hi @chrismattmann, I'm interested in taking up this project.

**Comment by chrismattmann** [comment]
awesome @ThejanW let's do it!
