### ISSUE TITLE
Upgrade Apache Solr to latest version

### ISSUE THREAD

**Issue by chrismattmann** [apache/drat#114]
Upgrade DRAT's use of Apache Solr to the latest version

**Comment by tanmaylaud** [comment]
hi, is this issue still active?

**Comment by chrismattmann** [comment]
it's as active as someone who has time to work on it? :) Got some time, @tanmaylaud ?

**Comment by tanmaylaud** [comment]
> it's as active as someone who has time to work on it? :) Got some time, @tanmaylaud ?

@chrismattmann  Yes :) . I am new to the code. Could you please provide a few starting pointers?

**Comment by venkatrammovva** [comment]
Hi @chrismattmann 

I have gone through the code and noticed that Apache Solr does not support deploying as a war into application containers like Tomcat anymore. Please refer to the following link for their reasoning behind this 

Link: https://cwiki.apache.org/confluence/display/solr/WhyNoWar

And new versions of Solr come with their own container start and stop scripts. To get the integration working, we have to use the maven download plugin and repackage it in our distribute goal. We may also have to modify the start script of drat to also start Solr separately and modify the Solr URL in the index call. 

If this sounds ok, please let me know. I will make the changes, test them as well as I can. 

Thank you!

**Comment by chrismattmann** [comment]
yes @venkatrammovva please start on it and we'll get it integrated
