### ISSUE TITLE
Take next steps on Proteus - evolve DRAT web interface

### ISSUE THREAD

**Issue by chrismattmann** [apache/drat#115]
Take the next steps on the Proteus interface. Specifically:

1. Allow for more bin/drat options in the interface, and cleanup
2. Allow for simultaneous users to use DRAT from the same cockpit interface (potentially by tagging projects, similar to DRAT stats)
3. Add more D3 visualizations.

**Comment by ahmedifhaam** [comment]
@chrismattmann hi, I like to work on this project for GSOC. I tried running the system and proteus too. It would be very helpful if i can know what should i do next ?

**Comment by chrismattmann** [comment]
thanks for your comment @ahmedifhaam i will reply to your email on the dev list thanks!

**Comment by ahmedifhaam** [comment]
@chrismattmann im trying to contact you in maling list and personal mail too regarding this gsoc project please contact me Thanks a lot

**Comment by chrismattmann** [comment]
I will contact you sorry have been out of the office. Will reach out tonight!

**Comment by chrismattmann** [comment]
Dear @ahmedifhaam I've reached out to you via email and also Slack. thanks.

**Comment by chrismattmann** [comment]
done!
