### ISSUE TITLE
Set up DRAT to weekly scan the ASF full Github

### ISSUE THREAD

**Issue by chrismattmann** [apache/drat#116]
Scan all ASF projects on Github using DRAT stats, and then publish a D3 DRAT viz page with latest scan

**Comment by buggtb** [comment]
Do we have, or can we get an ASF VM for this?

**Comment by chrismattmann** [comment]
yep we have one, drat.apache.org.
Current projects running there:

http://drat.apache.org/demo/ - Proteus live scan, pre-release 1.0
http://drat.apache.org/asfgit/ - Proteus D3 viz, pre-release 1.0
