### ISSUE TITLE
"bin/oodt stop" won't stop tomcat causing system to go out of memory

### ISSUE THREAD

**Issue by IMS94** [apache/drat#128]
I was testing OODT with DRAT and saw that the tomcat process created by the `bin/oodt start` command doesn't get killed/stopped on `bin/oodt stop` which causes the RAM to go out of memory if we run `oodt start` multiple times.

Below is an example in my machine where there were many tomcat processes running.

![drat_tomcat](https://user-images.githubusercontent.com/11285165/40099896-98a9bdfe-58ff-11e8-93d3-bb1b94468765.png)

**Comment by chrismattmann** [comment]
hmmm this sounds like a big problem @IMS94 how should we fix it?

**Comment by IMS94** [comment]
@chrismattmann We can call "tomcat stop" like command in [bin/oodt:158](https://github.com/apache/drat/blob/master/distribution/src/main/resources/bin/oodt#L158). But this depends on whether the Tomcat executable (or the command used to start Tomcat) also support stopping via a command.

**Comment by chrismattmann** [comment]
got it. Well let's try and make this robust thanks @IMS94 i'm available to test
