### ISSUE TITLE
Upgrade to JDK8

### ISSUE THREAD

**Issue by ottlinger** [apache/drat#134]
Is it possible to update to Java8 in all submodules?
I stumbled upon 1.6-compiler level in the pom.xml files.

Is there a reason for that?

Thanks

**Comment by chrismattmann** [comment]
no reason it shouldn't be JDK8 please upgrade.

**Comment by ottlinger** [comment]
@chrismattmann is DRAT built somewhere? I don't see a travis.yml and locally am unable to compile:
`[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /workspace2016/drat/proteus/src/test/java/backend/TestProcessDratWrapper.java:[50,37] incompatible types: java.util.List<backend.WorkflowItem> cannot be converted to java.util.List<org.apache.oodt.cas.workflow.structs.WorkflowInstance>
[ERROR] /workspace2016/drat/proteus/src/test/java/backend/TestProcessDratWrapper.java:[64,37] incompatible types: java.util.List<backend.WorkflowItem> cannot be converted to java.util.List<org.apache.oodt.cas.workflow.structs.WorkflowInstance>
[INFO] 2 errors 
`
anyone else?

**Comment by ottlinger** [comment]
The problem does not seem to be local only ....
https://travis-ci.org/ottlinger/drat/jobs/392890386

**Comment by ahmedifhaam** [comment]
@ottlinger This is happening because of the change we made. This test should fail. Earlier we were using WorkflowItem which is created by parsing the shell script output. But we are now using WorkflowInstance Object which is returned by XMlRpc by default. Since we may move AvroRpc and normally it was suggested to write tests with next phase i haven't changed it

**Comment by chrismattmann** [comment]
@ottlinger I fixed this. It builds fine now so please finish upgrading to JDK8.

**Comment by buggtb** [comment]
Be worth testing JDK 10 also, because in some other projects JDK 10 broke Tomcat for a start. I'll give it a whirl this week at some point.

**Comment by chrismattmann** [comment]
+1 thanks @buggtb
