### ISSUE TITLE
[upstream] Doesn't run under JDK10 due to OODT

### ISSUE THREAD

**Issue by buggtb** [apache/drat#136]
Tried to run DRAT on JDK 10 on Ubuntu and get:

`
Using CATALINA_BASE:   /home/bugg/drat/deploy/tomcat
Using CATALINA_HOME:   /home/bugg/drat/deploy/tomcat
Using CATALINA_TMPDIR: /home/bugg/drat/deploy/tomcat/temp
Using JRE_HOME:        /usr/lib/jvm/java-10-oracle/
Using CLASSPATH:       /home/bugg/drat/deploy/tomcat/bin/bootstrap.jar:/home/bugg/drat/deploy/tomcat/bin/tomcat-juli.jar
Tomcat started.
Resource Manager started PID file (/home/bugg/drat/deploy/resmgr/run/cas.resmgr.pid).
Workflow Manager started PID file (/home/bugg/drat/deploy/workflow/run/cas.workflow.pid).
-Djava.ext.dirs=/home/bugg/drat/deploy/filemgr/lib is not supported.  Use -classpath instead.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
-Djava.ext.dirs=/home/bugg/drat/deploy/resmgr/lib is not supported.  Use -classpath instead.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
-Djava.ext.dirs=/home/bugg/drat/deploy/workflow/lib is not supported.  Use -classpath instead.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
`
This will be an upstream OODT issue so we'll track it there.
https://issues.apache.org/jira/browse/OODT-988

**Comment by chrismattmann** [comment]
yep this is an OODT issue.
