### ISSUE TITLE
Consider a search bar for projects in project view viz

### ISSUE THREAD

**Issue by chrismattmann** [apache/drat#166]
bq. from @tdunning there are lots of mapr projects. It would help a lot to have some kind of nav ... an alphabet .. a search bar

**Comment by ahmedifhaam** [comment]
@chrismattmann i have added a search field for this table but it wont search the string in location field but i may be able to make it search on it also but it would slow down the ui and search. What should i do ?

**Comment by chrismattmann** [comment]
i don't understand your comment @ahmedifhaam why couldn't we search on the URL? I think we should search at a minimum on the project name field...

**Comment by chrismattmann** [comment]
fixed in #170
