### ISSUE TITLE
Create an issue and pull request templates

### ISSUE THREAD

**Issue by brenopolanski** [apache/drat#188]
GitHub now supports **issue templates** via a markdown file called `issue_template.md` in the root or `.github/` folder of repo!

There is also added support for **pull request** templates via a markdown file called `pull_request_template.md` in the root or `.github/` folder of repo!

About: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by brenopolanski** [comment]
## Suggestions:

### :memo: `bug_report.md`

```
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''
---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version:**
[e.g. 0.4.5]

**Additional context**
Add any other context about the problem here.
```

### :memo: `feature_request.md`

```
---
name: Feature request
about: Suggest an idea for this project
title: ''
labels: ''
assignees: ''
---

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.
```

**Comment by ottlinger** [comment]
Thanks for your contribution and the idea, @brenopolanski 
As DRAT is part of the ASF any contribution needs to be checked for a proper licensing.

Thus we should add a paragraph that states:
[ ] I'm okay with my contribution to [DRAT](https://drat.apache.org/)@[ASF](https://www.apache.org/) under ASF 2.0.
[ ] I already filed a [ICLA](https://www.apache.org/licenses/icla.pdf) (Contributor's License Agreement)

Not sure if that's legally correct, but I assume it's needed for proper compliance.

Any ideas @chrismattmann ?

**Comment by brenopolanski** [comment]
Yeah @ottlinger make sense :+1:
