### ISSUE TITLE
Add instructions for how to exclude a directory

### ISSUE THREAD

**Issue by tbpalsulich** [apache/drat#19]
For example, if you crawl a subversion repository, you probably don't want to crawl the `repo/.svn` directory. How do you configure DRAT to skip over it?

**Comment by chrismattmann** [comment]
Is there a PR for this @tpalsulich ?

**Comment by tbpalsulich** [comment]
Nope. ;) Legitimate question. Happy to give a PR for the drat script once I know how, though.

**Comment by lewismc** [comment]
Mmmmmm....
Do you have source code for RAT?
What happens if source is not in SVN? e.g. file system... as most of the code is? Or even here on GH?
It would be a really nice switch @tpalsulich BTW I think there is one .svn hidden directory per underlying physical directory, so a patch to skip would be significant in decreasing runtime execution time!

**Comment by chrismattmann** [comment]
One of my goals here would be to wire in Push Pull to download remote code. I would love to have  DRAT UI that is the main UI for DRAT, and it looks like a simple URL box, where we provide the URL to source code (it could be a file URL) with autocomplete, and then we click a Go button! The result of this would be a pie chart/histogram with D3.js with the code analysis.

**Comment by lewismc** [comment]
Mazi has been shining recently with his D3 skillsm ;)
I think it is an excellent idea to visualize the results @chrismattmann there is absolutely no doubt about it.
I would really like to see 'which' files are in violation of auditing... e.g. a list, packages they belong to, etc. I know we can see physical results within /data directory as well as aggregated results within CSV... but UI would be killer @chrismattmann

**Comment by chrismattmann** [comment]
@tpalsulich @lewismc the way to exclude a directory is to check out the CrawlerAPI for OODT CAS Crawler - you can basically use Actions also PreCond comparators. We can basically add a new PreConditionComprator called ExcludeDirector, see the interface here: 

http://svn.apache.org/repos/asf/oodt/trunk/metadata/src/main/java/org/apache/oodt/cas/metadata/preconditions/PreConditionComparator.java

So what you can do is:
1. Develop a PreConditionComparator that is a RegExExcludePreCond comparator
2. Evaluate the regex against the file
3. If it matches the regex, return false which in turn will prevent metadata from being generated, which in turn will prevent that directory or file, etc., from being crawled.

So, if someone does: 
 ./bin/drat crawl --exclude "*.svn" 

This should translate into a call to 

./crawler/bin/crawler_launcher ..params.. --preCondIds RegExExcludeComparator ...etc

**Comment by karanjeets** [comment]
Thanks a lot @chrismattmann 

I have developed a RegEx Comparator using the above instructions and tested with DRAT. It works well. One can use the below regex string for validating a UNIX-like file path.

``` java
(/[a-z0-9_-]+)+(/KEYWORD)(/[a-z0-9_-]+[.]?[a-z0-9_-]*)*(/)?
```

```
where KEYWORD can be replaced with "[.]+svn" or "[.]+gitignore" 
to exclude .svn folders or Git files.
```

However, I can see that crawler traverses through all the restricted paths and then rejects it. Is it possible to reject the complete folder at once ?

**Comment by lewismc** [comment]
#wikipage

On Sunday, October 4, 2015, Karanjeet Singh notifications@github.com
wrote:

> Thanks a lot @chrismattmann https://github.com/chrismattmann
> 
> I have developed a RegEx Comparator following the above instructions and
> tested with DRAT. It works well. One can use the below regex string for
> validating a UNIX-like file path.
> 
> (/[a-z0-9_-]+)+(/KEYWORD)(/[a-z0-9_-]+[.]?[a-z0-9_-]_)_(/)?
> where KEYWORD can be replaced with "[.]+svn" or "[.]+gitignore" to exclude
> .svn folders or Git files.
> 
> However, I can see that crawler traverses through all the restricted paths
> and then rejects it. Is it possible to reject the complete folder at once ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chrismattmann/drat/issues/19#issuecomment-145328819.

## 

_Lewis_

**Comment by lewismc** [comment]
Nice job

On Sunday, October 4, 2015, Lewis John Mcgibbney lewis.mcgibbney@gmail.com
wrote:

> #wikipage
> 
> On Sunday, October 4, 2015, Karanjeet Singh <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Thanks a lot @chrismattmann https://github.com/chrismattmann
> > 
> > I have developed a RegEx Comparator following the above instructions and
> > tested with DRAT. It works well. One can use the below regex string for
> > validating a UNIX-like file path.
> > 
> > (/[a-z0-9_-]+)+(/KEYWORD)(/[a-z0-9_-]+[.]?[a-z0-9_-]_)_(/)?
> > where KEYWORD can be replaced with "[.]+svn" or "[.]+gitignore" to
> > exclude .svn folders or Git files.
> > 
> > However, I can see that crawler traverses through all the restricted
> > paths and then rejects it. Is it possible to reject the complete folder at
> > once ?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/chrismattmann/drat/issues/19#issuecomment-145328819.
> 
> ## 
> 
> _Lewis_

## 

_Lewis_

**Comment by chrismattmann** [comment]
Hi @karanjeets unfortunately know it still will traverse it, but sounds like you've got quite the PR already prepared. Can you send it in? Also please make sure to tie it to the command line too please :) :+1: (aka `./bin/drat crawl --exclude`. Cheers and thank you!

**Comment by karanjeets** [comment]
@chrismattmann @lewismc 
All done. I have raised a pull request for both OODT and DRAT. Please refer to OODT first as DRAT updates are dependent on that.

**Comment by chrismattmann** [comment]
now that https://github.com/apache/oodt/commit/944f662bd0a7be146cbce0c7f0966404a77e7617 is committed, we can progress on this @karanjeets

**Comment by karanjeets** [comment]
@chrismattmann 

Great. So will that commit be available for metadata 0.10, as DRAT is using the same ? 
The --exclude feature of DRAT is already committed in pull request #51 
Request you to please merge the same.

**Comment by chrismattmann** [comment]
Nope we need to update DRAT to use OODT 0.11 (trunk). Can you submit a PR for that @karanjeets ?

**Comment by chrismattmann** [comment]
Done in #53

**Comment by chrismattmann** [comment]
Err #51
