### ISSUE TITLE
Create Web Interface

### ISSUE THREAD

**Issue by tbpalsulich** [apache/drat#28]
We should create a simple web interface for DRAT. Go to the page, enter a URL (maybe a local file, a git repo, an svn repo, or something else), run DRAT, give a pretty status page of what DRAT is doing, and show a pretty results page.

**Comment by chrismattmann** [comment]
Here's a project description from the VPS semester of code that I wrote:

User Interface for the Distributed Release Audit Tool (DRAT)

The Distributed Release Audit Tool (DRAT) improves over the Apache RAT code audit tool in several ways. RAT is a command line tool and Java API and Maven plugin that audits a code base and its declared OSS licenses - if you say it's Apache2, RAT will check whether or not your source is Apache2 and produce a report that states what files are/aren't and why.

RAT has several problems, namely:

It doesn't scale to large code bases - running it on a 25k file and 10M LOC code base ran for ~4 weeks on a normal Linux server with 5GB memory and tons of hard disk and modern CPUs.
RAT's crawler is rudimentary and you have to use explicit white/black lists on what files to avoid or else it will be checking binary files for licenses.
RAT doesn't produce incremental output. It either completes and generates a log, or it doesn't.
DRAT improves upon RAT in several ways namely by addressing all of the above concerns. You can find DRAT here: https://github.com/chrismattmann/drat/ 

DRAT is a Map Reduce version of RAT using Apache Tika to automatically sort and classify the code base files; Apache OODT to index metadata and Tika information about those code files into Apache Solr; and OODT to produce a Map Reduce workflow that runs RAT incrementally on k-sized chunks of same-MIME-typed files (detected by Tika) and then producing incremental, per type logs, and then aggregating and reducing them into a combined log at the end.

DRAT currently has support for command line interaction, but no GUI. We need a GUI for DRAT that brings in neat visual interfaces like D3.js to show RAT log historgrams and code/source file reports and mappings. We need a search box in which a user inputs a URL pointing at a code base and the backend services for DRAT are invoked.

**Comment by ericmarcincuddy** [comment]
Presently looking into Bootstrap using either JSPs or Servlets able to query Solr and populate D3.js graphs and charts.

**Comment by chrismattmann** [comment]
great to hear @ericmarcincuddy

**Comment by chrismattmann** [comment]
I have some students at USC also working on this project now. I'll  include you on the emails.
