### ISSUE TITLE
Run DRAT on all of Apache SVN 

### ISSUE THREAD

**Issue by chrismattmann** [apache/drat#40]
Let's run DRAT on the whole Apache SVN repository and see how long it takes to complete and then come up with some stats on what worked, what didn't, what errors were seen, etc.

http://svn.apache.org/repos/asf/

The output of this task should be:
1. All DRAT logs for the code bases analyzed
2. The output Solr catalog of the code
3. A histogram analysis of the code types, etc.

**Comment by lewismc** [comment]
Bewm

On Wednesday, August 26, 2015, Chris Mattmann notifications@github.com
wrote:

> Let's run DRAT on the whole Apache SVN repository and see how long it
> takes to complete and then come up with some stats on what worked, what
> didn't, what errors were seen, etc.
> 
> http://svn.apache.org/repos/asf/
> 
> The output of this task should be:
> 1. All DRAT logs for the code bases analyzed
> 2. The output Solr catalog of the code
> 3. A histogram analysis of the code types, etc.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chrismattmann/drat/issues/40.

## 

_Lewis_

**Comment by lewismc** [comment]
How do you want to do this? I wonder if I could do it on people.apache.org~/lewismc ? wdyt? Or yours? Or somewhere else?

**Comment by chrismattmann** [comment]
How about on wrangler? :)

**Comment by lewismc** [comment]
Dynamite. Excellent idea. OK, onit. I'll stick it as a TODO for tomorrow lunch. I'll speak to Jane.

**Comment by chrismattmann** [comment]
Acked

**Comment by lewismc** [comment]
OK, Jane is getting my account. I'll make results available here ASAP.

**Comment by chrismattmann** [comment]
:+1:

**Comment by chrismattmann** [comment]
this is now done at http://drat.dyndns.org:8080/
