### ISSUE TITLE
Duplicate files detected and timestamped

### ISSUE THREAD

**Issue by lewismc** [apache/drat#44]
Whilst reviewing recent htrace 4.0 incubating RC I am getting results like the following

```
...
  /usr/local/drat/deploy/data/jobs/rat/1441639423619/input/dependency-reduced-pom.xml
  /usr/local/drat/deploy/data/jobs/rat/1441639423619/input/dependency-reduced-pom.xml_09072015_1123
```

This is the same file... seemingly being strangely timestamped and analyzed twice. I think this is a bug in drat master.

**Comment by chrismattmann** [comment]
thanks Lewis, it's actually not the same file. When copying data into the RAT working dir, sometimes files have the same name. To fix that I used a parameter on cp that takes filenames with the same name and timestamps them to prevent overwrites and collisions. The file contents may be the same, but the path in the analyzed source code isn't.

**Comment by lewismc** [comment]
Absolutely right @chrismattmann thanks
