### ISSUE TITLE
Add netstat as fallback to lsof command to check service status

### ISSUE THREAD

**Issue by karanjeets** [apache/drat#52]
In many systems, `lsof` command is reserved for root user and hence it may cause the drat script to fail. We can configure `netstat` as fallback for the same.

**Comment by chrismattmann** [comment]
@karanjeets you took care of this, right, if so please close.

**Comment by karanjeets** [comment]
@chrismattmann Yes. This has been taken care.

Replaced "lsof" with "nc" command. Related to PR #79
