### ISSUE TITLE
Configuring DRAT for TACC Wrangler

### ISSUE THREAD

**Issue by karanjeets** [apache/drat#54]
This thread is to discuss about DRAT's configuration and execution on TACC Wrangler. The draft workflow is as below:

https://docs.google.com/presentation/d/1QeuvwqLROCE888DtxVFEduGeL_KjQXdfT-XuHrJSkqI/edit?usp=sharing

**Comment by karanjeets** [comment]
The issue #53 is a sub-problem of this.

**Comment by lewismc** [comment]
@karanjeets what is the status of this please? I am kind of in limbo with the overall issue.

**Comment by karanjeets** [comment]
@lewismc 
I am working with Niall (from TACC) on this. Meanwhile, issue #53 needs to be resolved. Can you please help there ?

**Comment by lewismc** [comment]
Yep no probs.

On Friday, October 30, 2015, Karanjeet Singh notifications@github.com
wrote:

> @lewismc https://github.com/lewismc
> I am working with Niall (from TACC) on this. Meanwhile, issue #53
> https://github.com/chrismattmann/drat/issues/53 needs to be resolved.
> Can you please help there ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chrismattmann/drat/issues/54#issuecomment-152627285.

## 

_Lewis_

**Comment by smarru** [comment]
@karanjeets great work and insightful visualizations. I am following your updates to apache comdev list. I am intersted in your plumbings to Wrangler submissions. On a quick search I could not find the right code. Can you please point me to the code which does Wrangler submissions and loads Spark. I am trying to replicate your experiences on a different project working along with @chrismattmann. Thanks, Suresh

**Comment by karanjeets** [comment]
@smarru Thanks for the feedback and I am glad to know your interest in replicating this experience. As you might be aware, Wrangler employs the SLURM job scheduler - [Reference](https://portal.tacc.utexas.edu/user-guides/wrangler). I wrote couple of SLURM scripts embedding my configurations and job in it. Due to ongoing improvements and DRAT runs, the script code is sitting on Wrangler. As we are towards the end of auditing SVN projects, I will push this anytime soon.

I am interested to understand the project you are working on and hopefully then I will be able to provide better inputs. Let me shoot an email to you and we can take up from there.

**Comment by chrismattmann** [comment]
I believe this is now done.
