### ISSUE TITLE
Environment Variables Missing when Attempting to hit OODT File Manager API

### ISSUE THREAD

**Issue by sfrancus** [apache/drat#60]
I worked with @chrismattmann on this last night but when I tried to connect first to the OODT Product Service API using DRAT, I ran into two issues:
1) The Wiki page seems to be out of date (https://cwiki.apache.org/confluence/display/OODT/File+Manager+REST+API) since it says the API URLs are http://host/prodserver, when they now are http://host/fmprod

2) Several environment variables are missing by default, which cause 500 errors when hitting these URLs:
To use the Product Service APIs for File Manager, you need to set $FMPROD_HOME, which is defined as $DRAT_HOME/webapps/fmprod.

**Comment by lewismc** [comment]
Hi @sfrancus 

> 1) The Wiki page seems to be out of date (https://cwiki.apache.org/confluence/display/OODT/File+Manager+REST+API) since it says the API URLs are http://host/prodserver, when they now are http://host/fmprod

This has been addressed, I've just updated the wiki. Thank you for the attention to detail.

> 2) Several environment variables are missing by default, which cause 500 errors when hitting these URLs:
> To use the Product Service APIs for File Manager, you need to set $FMPROD_HOME, which is defined as $DRAT_HOME/webapps/fmprod. 

This is not true... I am able to use DRAT no problems with the following set.

```
124 #DRAT
125 export DRAT_HOME=$USR_LOCAL/drat/deploy
126 export WORKFLOW_HOME=$DRAT_HOME/workflow
127 export FILEMGR_HOME=$DRAT_HOME/filemgr
128 export PGE_ROOT=$DRAT_HOME/pge
129 export PCS_HOME=$DRAT_HOME/pcs
```

**Comment by lewismc** [comment]
Hope this helps.

**Comment by chrismattmann** [comment]
Hey @lewismc @sfrancus is trying to use the underlying FMProd OODT service which by default you don't need to run DRAT, but for Proteus is needed to show the UI. @sfrancus can you help us update the wiki?

**Comment by chrismattmann** [comment]
testing slack integration

**Comment by lewismc** [comment]
Hi @chrismattmann @sfrancus sorry, absolutely no context over and above trying to reproduce this myself and succeeding.
Issue description does not mention Slack but I am VERY interested to hear what you guys have in mind (although now I have an idea).

**Comment by lewismc** [comment]
+1 keep open folks... batter away sorry

**Comment by lewismc** [comment]
@sfrancus if you require write access to OODT wiki then please ask one of us. If not then please fire away and put the use case there. Thanks @chrismattmann for reopening

**Comment by sfrancus** [comment]
@lewismc 
So this issue occurred since for Proteus we're trying to get the last 20 files ingested by DRAT, which we can access via the File Manager RSS field (something like localhost:8080/fmprod/viewRecent?channel=ALL). However, when I hit that endpoint on my DRAT instance in-browser it returned:
javax.servlet.ServletException: null/rssconf.xml (No such file or directory)
    org.apache.oodt.cas.product.rss.RSSProductServlet.init(RSSProductServlet.java:116)
    org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:542)
    org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
    org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:151)
    org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:870)
    org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProto

@chrismattmann worked with me to resolve the issue and figured out that in one of the context.xml files $FMPROD_HOME was being referenced but was not set as an environment variable. He then told me to copy the relevant files 
(mkdir -p $DRAT_HOME/webapps/fmprod

chrismattmann [11:10 PM]11:10
cp -R $DRAT_HOME/tomcat/webapps/fmprod/WEB-INF/classes/*.xml $DRAT_HOME/webapps/fmprod

chrismattmann [11:10 PM]
then set

chrismattmann [11:10 PM]
$FMPROD_HOME to $DRAT_HOME/webapps/fmprod)

And restart Tomcat, which worked.

**Comment by lewismc** [comment]
So... is this a bug? 
Do you guys have a branch for Proteus?

**Comment by sfrancus** [comment]
Unfortunately we don't have a branch, we forked it. Here's the link:
https://github.com/sfrancus/drat
However we haven't changed any drat-specific code, all our changes are in the folder proteus.

**Comment by lewismc** [comment]
Can you make a branch for drat? Do you want me to?

**Comment by sfrancus** [comment]
A branch for Proteus in Drat, or a drat-branch in my Proteus fork?

**Comment by lewismc** [comment]
I am asking if you are working on a local branch which you push to remote @chrismattmann but on a branch apart from master?
Is there now 2 different DRAT codebases?

**Comment by sfrancus** [comment]
So my team has been working on a separate DRAT codebase (https://github.com/sfrancus/drat) which I forked a month ago. We have individual branches on that fork. When we had a stable build we planned to merge back to the main DRAT project.

**Comment by lewismc** [comment]
Fantastic. I saw some screen shots and I wondered which codebase they came from. This sounds excellent. 
DRAT is not such a dynamic codebase on core... so I think it would not be a huge issue to merge when you want. I suppose you and @chrismattmann have this established right?

**Comment by sfrancus** [comment]
I think so. @chrismattmann hasn't communicated any huge issues about the fork vs branch, and we made it clear that we aren't changing anything in DRAT/OODT (all we require is that there's no breaking changes, we won't use any gotcha hacks, just the promised API).

**Comment by lewismc** [comment]
Sounds grand. Really look forward to seeing a UI in DRAT. Is this ticket an issue anymore?

**Comment by chrismattmann** [comment]
yeah we're good here - I told them to fork and dev and make pull requests from their fork.

**Comment by chrismattmann** [comment]
the final home for proteus is here in my DRAT, which is the canonical upstream for the project.

**Comment by chrismattmann** [comment]
fixed
