### ISSUE TITLE
Getting CSV file with workflow ID

### ISSUE THREAD

**Issue by junsuhle** [apache/drat#62]
Started dynamic workflow with id 'f18d24f2-80f5-11e5-85f5-b129ee5c57a9'

Navigate to http://localhost:8080/opsui/ to view the OODT browser and http://localhost:8080/solr to view the Solr catalog.
Started dynamic workflow with id 'f9171374-80f5-11e5-85f5-b129ee5c57a9'

Navigate to http://localhost:8080/opsui/ to view the OODT browser and http://localhost:8080/solr to view the Solr catalog.
# 

So I think I can get csv file (# of notes/binaries/archives/standards/apache.. etc) by using workflow id above. 
However, looks like http://host/fmprod/data?productID=3abc2ec0-721e-11de-831c-abb3b8e32d26  (Download a product (by ID) from the CAS REST API) request
is nothing related to workflow id. How can we get REST request for workflow id? 
Moreover, which REST request gives us the workflow id (ex: Started dynamic workflow with id 'f18d24f2-80f5-11e5-85f5-b129ee5c57a9')

**Comment by karanjeets** [comment]
@junsuhle Can you please elaborate on what you are trying to achieve here ?

**Comment by junsuhle** [comment]
Hi Karanjeets, sorry for late response. I am trying to find final end point for csv file (contains licenses type) using workflow ID. In order to do it, I need to know two things (I think). 
1. End point for workflow ID (I think this one from log 
   "Started dynamic workflow with id 'f9171374-80f5-11e5-85f5-b129ee5c57a9") 
2. End point for csv file or license type using above workflow ID. If I don't need above workflow ID to get license type, disregard above one.

**Comment by junsuhle** [comment]
I solve this.

Getting productid for RatAggregateLog

/fmprod/viewRecent?channel=RatAggregateLog&typeID=urn:drat:RatAggregateLog

should be 1 per full DRAT run
so grab that RSS, CSS/Jquery selector the ID out

and 

/fmprod/data?productID=<some long UUID>

to get the output

**Comment by chrismattmann** [comment]
looks like we're good
