### ISSUE TITLE
Proteus (GUI for DRAT) proposed mid-tier API document (draft)

### ISSUE THREAD

**Issue by sfrancus** [apache/drat#63]
Hey guys,
It's Steven from the Proteus team. Since we all love REST stuff, I drafted up a midtier API concept that we're implementing for Proteus that can allow you to directly hit these endpoints instead of having to go through our GUI. I have a Google Doc link for it now but eventually I'll put it on APIary:
https://docs.google.com/document/d/1agFLNPKX-l01of0ojf_IC0ssD2S2LhBi9aQy-Bo_f_0/edit

Please let me know your thoughts.

**Comment by lewismc** [comment]
+1 APIARY would be an excellent idea for this.
Also, please check out Miredot for REST documentation.
You can contact Miredot and request a free open source license which will
last for 2 years.
Thanks

On Wed, Nov 4, 2015 at 10:46 AM, sfrancus notifications@github.com wrote:

> Hey guys,
> It's Steven from the Proteus team. Since we all love REST stuff, I drafted
> up a midtier API concept that we're implementing for Proteus that can allow
> you to directly hit these endpoints instead of having to go through our
> GUI. I have a Google Doc link for it now but eventually I'll put it on
> APIary:
> 
> https://docs.google.com/document/d/1agFLNPKX-l01of0ojf_IC0ssD2S2LhBi9aQy-Bo_f_0/edit
> 
> Please let me know your thoughts.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chrismattmann/drat/issues/63.

## 

_Lewis_

**Comment by chrismattmann** [comment]
@sfrancus @DalerAsrorov where we at here?
