### ISSUE TITLE
Proteus JS front-end issues too many REST call backs

### ISSUE THREAD

**Issue by chrismattmann** [apache/drat#69]
@DalerAsrorov the callbacks in the AngularJS make too many REST requests and bog down tomcat. It needs to be throttled.

**Comment by DalerAsrorov** [comment]
@chrismattmann I am currently working on it. Will be fixed.

**Comment by chrismattmann** [comment]
thanks @DalerAsrorov

**Comment by chrismattmann** [comment]
hey @DalerAsrorov where we at on this

**Comment by chrismattmann** [comment]
hey @DalerAsrorov did you ever fix this?

**Comment by DalerAsrorov** [comment]
Yes! The callbacks were much less than before. I tried it multiple times on my computer and it does less callbacks than it did before the issue came up.

**Comment by chrismattmann** [comment]
Cool can you send a pull request with the updates?

**Comment by chrismattmann** [comment]
@DalerAsrorov

**Comment by chrismattmann** [comment]
ping @DalerAsrorov

**Comment by chrismattmann** [comment]
fixed
