### ISSUE TITLE
org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: java.lang.Exception: org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException 	at org.apache.oodt.cas.filemgr.system.XmlRpcFileManagerClient.getTopNProducts(XmlRpcFileManagerClient.java:672) on calling fmprod

### ISSUE THREAD

**Issue by sfrancus** [apache/drat#72]
Hey all,
I'm getting this error when I try to hit the endpoint fmprod/viewRecent?channel=RatLog&id=urn:drat:RatLog on http://drat.dyndns.org:8080/proteus (it's the Proteus GUI). Anyone know what could be the cause? I can't reproduce it on my local machine.

**Comment by karanjeets** [comment]
This seems to be working fine as per the link below.
http://drat.dyndns.org:8080/fmprod/viewRecent?channel=RatLog&id=urn:drat:RatLog
