### ISSUE TITLE
DRAT does not detect .scala

### ISSUE THREAD

**Issue by lewismc** [apache/drat#87]
Recently when analyzing Sotera's [correlation-approximation](https://github.com/Sotera/correlation-approximation) I noticed that the Scala code is ignored.
We should extend DRAT detectors to ensure that Scala code is both detected and analyzed.

**Comment by chrismattmann** [comment]
need to update mime-partitioner.py for this..

**Comment by karanjeets** [comment]
I think this is handled in #93 
We just need to run a test and confirm.

**Comment by chrismattmann** [comment]
this is fixed in #93
