### ISSUE TITLE
Make website at drat.apache.org

### ISSUE THREAD

**Issue by chrismattmann** [apache/drat#98]
Now that we are at the ASF let's make a DRAT website, per these guidelines: 

https://www.apache.org/foundation/marks/pmcs#introduction

@wmburke

**Comment by chrismattmann** [comment]
test of G/H integration

**Comment by chrismattmann** [comment]
test 2

**Comment by shivikathapar** [comment]
![drat v2](https://user-images.githubusercontent.com/3753781/32203967-c775dc5a-bda3-11e7-86b7-64448931723e.png)

Hi everyone! I am excited to contribute to this project as a designer. This is the first pass for DRAT's website design. I would love to hear any feedback and comments.

**Comment by nipurndoshi** [comment]
I would love to be a part of this and contribute by coding the template designed by Shivika. 
Here's the simple technology stack on my mind for this:

1. Bootstrap v4.0.0 frontend library
2. jquery-3.2.1
3. html5+css3

**Comment by chrismattmann** [comment]
love it @shivikathapar and @nipunhere ! thank you i love the design yes, please pursue this. please go ahead and create a branch called site-dev and we can put the website there. Then you can submit some Pull Requests and we'll get this going. Thanks!

**Comment by chrismattmann** [comment]
i think we should also in this process create a "DRAT" logo. Any ideas? Some one doing the "face palm?" A distributed set of open doors?

**Comment by wmburke** [comment]
Thanks, @shivikathapar and @nipunhere.

Nipurn, keep me in the loop as you get things set up. I'm happy to help with these things as well.

For the logo, how about a bunch (distribution) of rats with feathers in their little, robin hood style hats?

**Comment by shivikathapar** [comment]
Thanks for the logo suggestions @chrismattmann and @wmburke! I will explore those further and share.

**Comment by ottlinger** [comment]
As reported in #103 there is no page shown at the moment - what do you think of my under-construction page at https://ottlinger.github.io/drat-in-progress

Feel free to file pull requests for missing information.

Any opinions?

**Comment by chrismattmann** [comment]
@ottlinger LOVE it! I will create a site-dev branch here in DRAT and then if you can submit a PR against it we can get GitPubSub set up and get this pushed out and part of the DRAT code base.

@shivikathapar @nipunhere then we could take your design and have it as a PR against site-dev:

**Comment by ottlinger** [comment]
@chrismattmann would a separate repository make sense as it may function as a transition repo?! Or would you create a separate drat-site-repo instead?!

RAT has a separate repository for that .... thanks.

**Comment by chrismattmann** [comment]
hey @ottlinger I think we can use the same repo just in a branch. We do that in OODT and it works out great. OK site-dev branch is up! http://github.com/apache/drat/tree/site-dev Have at it!

**Comment by chrismattmann** [comment]
Thanks for the great work @ottlinger I've filed https://issues.apache.org/jira/browse/INFRA-15489 to track pushing this to drat.apache.org via Gitpubsub

**Comment by ottlinger** [comment]
Can anyone supply me with the following information about DRAT:
* Twitter-handle (if existing)
* Facebook-URL (if existing)
* Instagram-URL (if existing)
* LinkedIn-URL (if any)
* Mailing list (developer@drat.apache.org?! or users@drat.apache.org)
* Base location of the main repository - or is https://github.com/apache/drat the main repo and no ASF-repo exists at all?

I want to tweak the current page before it goes live via [INFRA-15489](https://issues.apache.org/jira/browse/INFRA-15489)

Thanks for your help.

**Comment by chrismattmann** [comment]
hi @ottlinger 👍 
Twitter-handle (if existing) - * we don't have one, but would be great to create @ApacheDRAT *
Facebook-URL (if existing) - * don't have one *
Instagram-URL (if existing) - * don't have one *
LinkedIn-URL (if any) - * don't have one *
Mailing list (developer@drat.apache.org?! or users@drat.apache.org) - *dev@drat.apache.org*
Base location of the main repository - or is https://github.com/apache/drat the main repo and no ASF-repo exists at all? - yep http://github.com/apache/drat/ since we use gitbox.apache.org so that's the apache repo... :)

**Comment by chrismattmann** [comment]
ping @shivikathapar and @nipunhere we have a temp website up, can we get going on the actual website thanks!

**Comment by chrismattmann** [comment]
ping @shivikathapar @nipunhere again

**Comment by nipurndoshi** [comment]
Hi @chrismattmann, @wmburke I have just generated a PR for the website here:
https://github.com/apache/drat/pull/110

**Comment by wmburke** [comment]
Thanks, @nipunhere.
@chrismattmann This doesn't seem to have gone live as of yet. Is there a specific hold-up or is it just because of the holidays? Anything I can do to help push it through?

**Comment by chrismattmann** [comment]
all done by merging #111
